# Generated by Django 4.0.6 on 2022-08-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('relacion', models.CharField(max_length=30)),
                ('fechaNacimiento', models.DateField()),
            ],
        ),
    ]
