# Generated by Django 4.0.6 on 2022-08-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiares',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
