# Generated by Django 4.0.6 on 2022-08-03 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0002_familiares_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiares',
            name='relacion',
        ),
    ]
